global:
  awsRoleArn: arn:aws-test:iam::123456789012:role/myserviceaccount.default.sa.minimal.example.com
config:
  tokenAudience: sts.amazonaws.com
  podIdentityWebhookMap:
    enabled: true
    data:
      "{{ .Release.Namespace }}/myserviceaccount":
        RoleARN: "{{ .Values.global.awsRoleArn }}"
        Audience: "{{ .Values.config.tokenAudience }}"
