apiVersion: v2
name: values
description: Pipeline the yaml from the values. Useful to deploy custom resources through Terraform.
home: https://github.com/jkroepke/helm-charts
version: 1.0.5
maintainers:
  - name: jkroepke
    email: github@jkroepke.de
    url: https://github.com/jkroepke
keywords:
  - helm
  - value
  - values
sources:
  - https://github.com/jkroepke/helm-charts
