apiVersion: v2
name: github-runner-agent
description: A Helm chart to deploy github runner for Kubernetes.
type: application
version: 1.1.1
home: https://github.com/jkroepke/helm-charts
sources:
  - https://github.com/myoung34/docker-github
  - https://github.com/jkroepke/helm-charts
maintainers:
  - name: Jan-Otto Kr√∂pke
    url: https://github.com/jkroepke
