apiVersion: v2
name: keycloak-config-cli
description: Import JSON-formatted configuration files into Keycloak - Configuration as Code for Keycloak.
home: https://github.com/adorsys/keycloak-config-cli
version: 1.3.3
# renovate: docker=adorsys/keycloak-config-cli
appVersion: 6.0.1
maintainers:
  - name: jkroepke
    email: github@jkroepke.de
    url: https://github.com/jkroepke
keywords:
  - keycloak
  - config
  - import
  - json
  - continuous-integration
  - keycloak-config-cli
sources:
  - https://github.com/adorsys/keycloak-config-cli
