apiVersion: v2
name: github-exporter
description: exporter for export github metrics
home: https://github.com/jkroepke/github_exporter
version: 1.1.0
# renovate: image=jkroepke/github_exporter
appVersion: 1.6.0
maintainers:
  - name: jkroepke
    email: github@jkroepke.de
    url: https://github.com/jkroepke
keywords:
  - github_exporter
  - config
  - exporter
  - github
  - prometheus
sources:
  - https://github.com/adorsys/github_exporter
