name: CI
permissions: {}

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    # name: Lint and Test Charts
    runs-on: ubuntu-24.04
    env:
      CT_BUILD_ID: '${{ github.run_id }}'
      CT_CONFIG: charts/ct.yaml
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          # renovate: github=helm/helm
          version: v4.1.0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          # renovate: github=helm/chart-testing
          version: v3.14.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed)"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_list=\"${changed//$'\n'/ }\"" >> "$GITHUB_OUTPUT"
          fi

      - name: install helm unittest plugin
        if: steps.list-changed.outputs.changed == 'true'
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 1.0.3 --verify=false

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Apply Gateway API CRDs
        run: kubectl apply -k https://github.com/kubernetes-sigs/gateway-api/config/crd
        if: steps.list-changed.outputs.changed == 'true'

      - name: Apply Prometheus Operator CRDs (unless for charts already installing it)
        env:
          CHANGED_LIST: ${{ steps.list-changed.outputs.changed_list }}
        run: |
          # Always run unless only changed chart is one of impacted charts
          echo "List is: $CHANGED_LIST"
          if [ "$CHANGED_LIST" = '"charts/kube-prometheus-stack"' ] || [ "$CHANGED_LIST" = '"charts/prometheus-operator-crds"' ]; then
            echo "Skipping install"
          else
            helm install prometheus-operator-crds oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
          fi
        if: steps.list-changed.outputs.changed == 'true'

      - uses: stackrox/kube-linter-action@v1
        with:
          directory: "${{ steps.list-changed.outputs.changed_list }}"

      - name: Run chart-testing (install)
        run: ct install --debug --excluded-charts amazon-eks-pod-identity-webhook,keycloak-config-cli

  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@12562e48d7059cf666c43a4ecb0d3b5a2b31bd9e # v8.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          # VALIDATE_CHECKOV: true - always scans everything and all charts have too much errors
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ENV: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          # VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_PYTHON: true
          VALIDATE_RENOVATE: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_XML: true
